layout_spectrum: 0.9999106
typography_spectrum: 0.5721881
color:
  saturation: 0.8493657
  lightness: 0.3494076
  brandStrength: 0.6065788
  rhythmicContrast: 0.7136762
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Bali
